# docker container to build the debian packages.
# base image that should not change, so these steps are not unnecessarily done
# on each sourcehut build job

FROM docker.io/library/debian:stable AS builder
ENV PATH="/venv/bin:/root/.local/bin:$PATH"

ENV DEBFULLNAME=IGImonster
ENV EMAIL=igimonster@mailbox.org
ENV GOBIN=/tmp/gobin
ENV PLUGINS="facebook signal telegram skype hackernews mattermost steam discord whatsapp"
ENV POETRY_EXTRAS="facebook signal telegram skype mattermost steam discord"

RUN echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates curl python3-slixmpp-lib

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
  devscripts \
  debhelper-compat \
  dwz \
  python3-dev \
  libffi-dev \
  cython3 \
  dh-virtualenv \
  ca-certificates \
  curl \
  golang-src/bullseye-backports \
  golang-go/bullseye-backports

RUN go install github.com/go-python/gopy@latest
RUN go install golang.org/x/tools/cmd/goimports@latest
RUN mv $GOBIN/gopy $GOBIN/goimports /usr/local/bin
RUN python3 -m pip install pybindgen
