FROM docker.io/library/python:3.9-slim AS builder

RUN echo "deb http://deb.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt update -y && apt install -yt bullseye-backports golang

RUN apt-get install -y --no-install-recommends curl rustc cargo gcc libssl-dev make

RUN python3 -m pip install wheel pybindgen
RUN curl -fL https://install.python-poetry.org | python3 - || cat /poetry-installer-error-*

ENV PATH=/root/.local/bin:$PATH

ENV GOBIN="/usr/local/bin"
RUN go install github.com/go-python/gopy@latest && \
    go install golang.org/x/tools/cmd/goimports@latest

WORKDIR /build
COPY poetry.lock \
     pyproject.toml \
     README.md \
     /build/
COPY slidge /build/slidge
COPY tests/ /build/tests
COPY dev/build.py /build/dev/build.py
COPY dev/assets /build/dev/assets
COPY dev/confs /build/dev/confs
COPY docs/ /build/docs

ARG TARGETARCH
RUN poetry build
# only run tests and build docs for the amd64 container for speed
RUN if [ "$TARGETARCH" = "amd64" ]; then poetry install --all-extras; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then poetry run ruff slidge; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then poetry run mypy slidge; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then poetry run pytest tests; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then poetry run black slidge --check; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then cd docs; make html; fi
RUN if [ "$TARGETARCH" = "amd64" ]; then cd docs/build/html; tar czf /slidge-docs.tar.gz .; fi
# create a /slidge-docs.tar.gz file for arm64 to avoid failing docker build
RUN if [ "$TARGETARCH" = "arm64" ]; then touch /slidge-docs.tar.gz; fi

FROM scratch
COPY --from=builder /slidge-docs.tar.gz /slidge-docs.tar.gz
COPY --from=builder ./build/dist/* /dist/