FROM docker.io/library/python:3.9-slim AS builder

RUN echo "deb http://deb.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt update -y && apt install -yt bullseye-backports golang

RUN apt-get install -y --no-install-recommends curl rustc cargo gcc libssl-dev make

RUN python3 -m pip install wheel pybindgen
RUN curl -fL https://install.python-poetry.org | python3 - || cat /poetry-installer-error-*

ENV PATH=/root/.local/bin:$PATH
# furo (sphinx theme) cannot install without that,
# cf https://github.com/python-poetry/poetry/pull/7358
RUN poetry config installer.modern-installation false
RUN poetry config experimental.new-installer true

ENV GOBIN="/usr/local/bin"
RUN go install github.com/go-python/gopy@latest && \
    go install golang.org/x/tools/cmd/goimports@latest

WORKDIR /build
COPY poetry.lock \
     pyproject.toml \
     README.md \
     /build/
COPY slidge /build/slidge
COPY tests/ /build/tests
COPY dev/ /build/dev
COPY docs/ /build/docs

ARG TARGETARCH
RUN poetry build
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      poetry install --all-extras; \
      poetry run mypy slidge; \
      poetry run pytest tests; \
      poetry run black slidge --check; \
      cd docs; \
      make html; \
      cd build/html; tar czf /slidge-docs.tar.gz .;\
    fi
RUN touch /slidge-docs.tar.gz

FROM scratch
COPY --from=builder /slidge-docs.tar.gz /slidge-docs.tar.gz
COPY --from=builder ./build/dist/* /dist/