FROM docker.io/library/debian:stable

RUN apt-get update && apt-get install wget gpg -y python3 python3-pip

# trust the repo's key
RUN wget -O- http://deb.slidge.im/repo/slidge.gpg.key \
  |gpg --dearmor \
  |tee /usr/share/keyrings/slidge.gpg > /dev/null
# add the repo, replace 'release' with 'nightly' if you're feeling adventurous
RUN echo "deb [signed-by=/usr/share/keyrings/slidge.gpg] http://deb.slidge.im/repo/debian release main" \
  > /etc/apt/sources.list.d/slidge.list

RUN echo "deb [signed-by=/usr/share/keyrings/slidge.gpg] http://deb.slidge.im/repo/debian nightly main" \
  >> /etc/apt/sources.list.d/slidge.list

RUN apt-get install -y

RUN pip install pybadges

COPY ./make-badge.sh /

ENTRYPOINT ["/make-badge.sh"]
