# container to build tdlib. example usage:
# docker buildx build --platform linux/i386 --file tdlib-build-dockerfile . -o /tmp/tdlib

FROM docker.io/library/debian:stable AS builder-tdlib

# everything telegram/tdlib-specific would be improved, ie removed, if we fixed
# https://github.com/pylakey/aiotdlib/issues/50

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y git g++ cmake zlib1g-dev gperf libssl-dev
RUN git clone https://github.com/pylakey/td --depth 1
RUN mkdir td/build
WORKDIR td/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tdlib/ -DTD_ENABLE_LTO=ON ..
RUN CMAKE_BUILD_PARALLEL_LEVEL=$(grep -c processor /proc/cpuinfo) cmake --build . --target install
RUN ls -la /tmp/tdlib/lib

FROM scratch AS tdlib
COPY --from=builder-tdlib /tmp/tdlib/lib /
