name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --bare "https://truenicoco:${GITHUB_TOKEN}@github.com/truenicoco/slidge" . || exit 1
          git remote add --mirror=fetch mirror https://git.sr.ht/~nicoco/slidge || exit 1
          git fetch mirror +refs/heads/*:refs/remotes/origin/* || exit 1
          git push --force --mirror --prune origin || exit 1
